export const townInfo = {
  name: "Maplewood",
  tagline: "Where Heritage Meets Tomorrow",
  founded: 1847,
  population: 28500,
  description:
    "Nestled in the heart of rolling hills and ancient maple forests, Maplewood is a charming small town that seamlessly blends its rich historical heritage with modern community living. Our vibrant downtown, picturesque parks, and welcoming residents make this the perfect place to visit, study, or call home.",
  longDescription:
    "Maplewood stands as a testament to the enduring spirit of small-town America. Founded in 1847 by settlers drawn to the region's fertile valleys and majestic maple forests, our community has grown into a thriving hub of culture, education, and natural beauty. From the cobblestone streets of our historic downtown to the sprawling trails of Maple Grove Park, every corner tells a story. Today, Maplewood is home to renowned educational institutions, award-winning restaurants, artisan boutiques, and a calendar full of festivals that bring our community together year-round.",
  coordinates: { lat: 40.7128, lng: -74.006 },
  area: "12.5 square miles",
  elevation: "420 feet",
  climate: "Four distinct seasons with colorful autumns",
}

export const stores = [
  {
    id: "maple-general-store",
    name: "Maple General Store",
    category: "General Store",
    description: "Family-owned since 1952, offering local goods, artisan crafts, and everyday essentials.",
    image: "/placeholder.svg?height=400&width=600",
    address: "123 Main Street, Maplewood",
    phone: "(555) 111-2222",
    hours: "Mon-Sat: 8AM-8PM, Sun: 10AM-6PM",
    coordinates: { lat: 40.7138, lng: -74.008 },
    rating: 4.8,
    priceRange: "$$",
    featured: true,
  },
  {
    id: "artisan-marketplace",
    name: "The Artisan Marketplace",
    category: "Boutique",
    description: "Curated collection of handmade goods from local artists and craftspeople.",
    image: "/placeholder.svg?height=400&width=600",
    address: "45 Oak Avenue, Maplewood",
    phone: "(555) 222-3333",
    hours: "Tue-Sat: 10AM-6PM, Sun: 12PM-5PM",
    coordinates: { lat: 40.7145, lng: -74.005 },
    rating: 4.9,
    priceRange: "$$$",
    featured: true,
  },
  {
    id: "bookworm-haven",
    name: "Bookworm Haven",
    category: "Bookstore",
    description: "Independent bookstore with rare finds, local authors, and cozy reading nooks.",
    image: "/placeholder.svg?height=400&width=600",
    address: "78 Library Lane, Maplewood",
    phone: "(555) 333-4444",
    hours: "Daily: 9AM-9PM",
    coordinates: { lat: 40.7125, lng: -74.003 },
    rating: 4.7,
    priceRange: "$$",
    featured: false,
  },
  {
    id: "maple-outdoors",
    name: "Maple Outdoors",
    category: "Outdoor Gear",
    description: "Everything you need for hiking, camping, and exploring our beautiful trails.",
    image: "/placeholder.svg?height=400&width=600",
    address: "200 Trail Road, Maplewood",
    phone: "(555) 444-5555",
    hours: "Mon-Sat: 9AM-7PM, Sun: 10AM-5PM",
    coordinates: { lat: 40.7155, lng: -74.012 },
    rating: 4.6,
    priceRange: "$$$",
    featured: true,
  },
  {
    id: "vintage-treasures",
    name: "Vintage Treasures",
    category: "Antiques",
    description: "Antiques and vintage collectibles spanning three floors of discoveries.",
    image: "/placeholder.svg?height=400&width=600",
    address: "156 Heritage Street, Maplewood",
    phone: "(555) 555-6666",
    hours: "Wed-Sun: 11AM-5PM",
    coordinates: { lat: 40.7118, lng: -74.007 },
    rating: 4.5,
    priceRange: "$$",
    featured: false,
  },
  {
    id: "green-thumb-nursery",
    name: "Green Thumb Nursery",
    category: "Garden Center",
    description: "Local plants, gardening supplies, and expert advice for your garden.",
    image: "/placeholder.svg?height=400&width=600",
    address: "890 Garden Way, Maplewood",
    phone: "(555) 666-7777",
    hours: "Daily: 8AM-6PM (Seasonal)",
    coordinates: { lat: 40.7095, lng: -74.015 },
    rating: 4.8,
    priceRange: "$$",
    featured: false,
  },
]

export const restaurants = [
  {
    id: "maple-house-bistro",
    name: "Maple House Bistro",
    category: "American",
    cuisine: "Farm-to-Table",
    description:
      "Upscale dining featuring locally-sourced ingredients and seasonal menus in a restored Victorian home.",
    image: "/placeholder.svg?height=400&width=600",
    address: "100 Maple Avenue, Maplewood",
    phone: "(555) 800-1001",
    hours: "Tue-Sun: 5PM-10PM",
    coordinates: { lat: 40.7142, lng: -74.006 },
    rating: 4.9,
    priceRange: "$$$$",
    featured: true,
    specialties: ["Maple-Glazed Duck", "Seasonal Tasting Menu", "Local Wine Selection"],
  },
  {
    id: "riverside-cafe",
    name: "Riverside Café",
    category: "Café",
    cuisine: "American",
    description: "Casual waterfront dining with stunning views, fresh coffee, and hearty breakfast all day.",
    image: "/placeholder.svg?height=400&width=600",
    address: "250 River Road, Maplewood",
    phone: "(555) 800-1002",
    hours: "Daily: 7AM-4PM",
    coordinates: { lat: 40.7158, lng: -74.002 },
    rating: 4.7,
    priceRange: "$$",
    featured: true,
    specialties: ["Eggs Benedict", "Belgian Waffles", "Artisan Coffee"],
  },
  {
    id: "bella-notte",
    name: "Bella Notte",
    category: "Italian",
    cuisine: "Italian",
    description: "Authentic Italian cuisine with handmade pasta and wood-fired pizzas in a romantic setting.",
    image: "/placeholder.svg?height=400&width=600",
    address: "67 Main Street, Maplewood",
    phone: "(555) 800-1003",
    hours: "Mon-Sat: 11AM-10PM, Sun: 4PM-9PM",
    coordinates: { lat: 40.7135, lng: -74.008 },
    rating: 4.8,
    priceRange: "$$$",
    featured: true,
    specialties: ["Truffle Risotto", "Margherita Pizza", "Tiramisu"],
  },
  {
    id: "golden-dragon",
    name: "Golden Dragon",
    category: "Asian",
    cuisine: "Chinese",
    description: "Family-owned Chinese restaurant serving traditional recipes for over 40 years.",
    image: "/placeholder.svg?height=400&width=600",
    address: "89 Oak Street, Maplewood",
    phone: "(555) 800-1004",
    hours: "Daily: 11AM-9:30PM",
    coordinates: { lat: 40.7128, lng: -74.004 },
    rating: 4.5,
    priceRange: "$$",
    featured: false,
    specialties: ["Kung Pao Chicken", "Dim Sum", "Peking Duck"],
  },
  {
    id: "taco-fiesta",
    name: "Taco Fiesta",
    category: "Mexican",
    cuisine: "Mexican",
    description: "Vibrant Mexican eatery with street tacos, fresh margaritas, and lively atmosphere.",
    image: "/placeholder.svg?height=400&width=600",
    address: "45 Fiesta Lane, Maplewood",
    phone: "(555) 800-1005",
    hours: "Daily: 11AM-11PM",
    coordinates: { lat: 40.7148, lng: -74.01 },
    rating: 4.6,
    priceRange: "$$",
    featured: false,
    specialties: ["Street Tacos", "Guacamole", "Churros"],
  },
  {
    id: "the-grill-room",
    name: "The Grill Room",
    category: "Steakhouse",
    cuisine: "American",
    description: "Premium steaks and seafood in an elegant, classic American steakhouse setting.",
    image: "/placeholder.svg?height=400&width=600",
    address: "300 Premium Drive, Maplewood",
    phone: "(555) 800-1006",
    hours: "Mon-Sat: 5PM-11PM",
    coordinates: { lat: 40.7165, lng: -74.007 },
    rating: 4.8,
    priceRange: "$$$$",
    featured: true,
    specialties: ["Dry-Aged Ribeye", "Lobster Tail", "Creamed Spinach"],
  },
  {
    id: "sunrise-bakery",
    name: "Sunrise Bakery & Café",
    category: "Bakery",
    cuisine: "Bakery",
    description: "Artisan breads, pastries, and light lunch options baked fresh daily.",
    image: "/placeholder.svg?height=400&width=600",
    address: "12 Morning Street, Maplewood",
    phone: "(555) 800-1007",
    hours: "Daily: 6AM-3PM",
    coordinates: { lat: 40.7122, lng: -74.009 },
    rating: 4.9,
    priceRange: "$",
    featured: false,
    specialties: ["Croissants", "Sourdough", "Cinnamon Rolls"],
  },
  {
    id: "sushi-zen",
    name: "Sushi Zen",
    category: "Japanese",
    cuisine: "Japanese",
    description: "Fresh sushi and traditional Japanese dishes in a minimalist, tranquil setting.",
    image: "/placeholder.svg?height=400&width=600",
    address: "188 Zen Way, Maplewood",
    phone: "(555) 800-1008",
    hours: "Tue-Sun: 12PM-10PM",
    coordinates: { lat: 40.7138, lng: -74.003 },
    rating: 4.7,
    priceRange: "$$$",
    featured: false,
    specialties: ["Omakase", "Dragon Roll", "Ramen"],
  },
]

export const hostels = [
  {
    id: "maplewood-inn",
    name: "The Maplewood Inn",
    category: "Boutique Hotel",
    description: "Charming boutique hotel in a restored 1890s mansion with modern amenities and personalized service.",
    image: "/placeholder.svg?height=400&width=600",
    address: "500 Heritage Lane, Maplewood",
    phone: "(555) 900-1001",
    email: "reservations@maplewoodinn.com",
    coordinates: { lat: 40.7145, lng: -74.005 },
    rating: 4.9,
    priceRange: "$$$",
    amenities: ["Free WiFi", "Breakfast Included", "Parking", "Concierge", "Garden"],
    rooms: 24,
    featured: true,
  },
  {
    id: "riverside-lodge",
    name: "Riverside Lodge",
    category: "Lodge",
    description: "Rustic-modern lodge overlooking the Maple River with cozy rooms and outdoor activities.",
    image: "/placeholder.svg?height=400&width=600",
    address: "800 River View Drive, Maplewood",
    phone: "(555) 900-1002",
    email: "stay@riverisidelodge.com",
    coordinates: { lat: 40.7162, lng: -74.001 },
    rating: 4.7,
    priceRange: "$$",
    amenities: ["River Views", "Kayak Rental", "Fire Pits", "Restaurant", "Pet Friendly"],
    rooms: 36,
    featured: true,
  },
  {
    id: "budget-stay",
    name: "Maplewood Budget Stay",
    category: "Hostel",
    description: "Clean, affordable accommodation perfect for backpackers and budget travelers.",
    image: "/placeholder.svg?height=400&width=600",
    address: "220 Traveler Street, Maplewood",
    phone: "(555) 900-1003",
    email: "info@budgetstay.com",
    coordinates: { lat: 40.7118, lng: -74.011 },
    rating: 4.3,
    priceRange: "$",
    amenities: ["Shared Kitchen", "Lounge", "Lockers", "Free WiFi", "Laundry"],
    rooms: 50,
    featured: false,
  },
  {
    id: "campus-suites",
    name: "Campus Suites",
    category: "Extended Stay",
    description: "Modern suites near the university, ideal for visiting families and extended stays.",
    image: "/placeholder.svg?height=400&width=600",
    address: "150 University Way, Maplewood",
    phone: "(555) 900-1004",
    email: "book@campussuites.com",
    coordinates: { lat: 40.7098, lng: -74.008 },
    rating: 4.5,
    priceRange: "$$",
    amenities: ["Kitchenette", "Study Desk", "Gym", "Pool", "Business Center"],
    rooms: 80,
    featured: false,
  },
  {
    id: "maple-grove-cabins",
    name: "Maple Grove Cabins",
    category: "Cabins",
    description: "Secluded cabins nestled in the forest near Maple Grove Park for nature lovers.",
    image: "/placeholder.svg?height=400&width=600",
    address: "1500 Forest Trail, Maplewood",
    phone: "(555) 900-1005",
    email: "reserve@maplegrovecabins.com",
    coordinates: { lat: 40.7175, lng: -74.015 },
    rating: 4.8,
    priceRange: "$$$",
    amenities: ["Private Deck", "Hot Tub", "Fireplace", "BBQ", "Hiking Access"],
    rooms: 12,
    featured: true,
  },
  {
    id: "downtown-hotel",
    name: "Downtown Maplewood Hotel",
    category: "Hotel",
    description: "Full-service hotel in the heart of downtown with easy access to shops and restaurants.",
    image: "/placeholder.svg?height=400&width=600",
    address: "1 Main Street, Maplewood",
    phone: "(555) 900-1006",
    email: "info@downtownmaplewood.com",
    coordinates: { lat: 40.7135, lng: -74.007 },
    rating: 4.4,
    priceRange: "$$",
    amenities: ["Restaurant", "Bar", "Room Service", "Fitness Center", "Valet Parking"],
    rooms: 120,
    featured: false,
  },
]

export const attractions = [
  {
    id: "maple-grove-park",
    name: "Maple Grove Park",
    category: "Parks & Recreation",
    shortDescription:
      "A 200-acre natural sanctuary featuring hiking trails, scenic overlooks, and the famous Maple Falls.",
    fullDescription:
      "Maple Grove Park stands as the crown jewel of Maplewood's natural attractions. Spanning over 200 acres of pristine woodland, the park offers visitors an immersive experience in nature. The park features over 15 miles of well-maintained hiking trails ranging from easy family-friendly walks to challenging terrain for experienced hikers. The centerpiece is the magnificent Maple Falls, a 60-foot waterfall that cascades into a crystal-clear pool below. Throughout the seasons, the park transforms - from vibrant spring wildflowers to the spectacular autumn foliage that draws visitors from across the region.",
    image: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hours: "Dawn to Dusk, Year-round",
    admission: "Free",
    address: "1200 Parkway Drive, Maplewood",
    phone: "(555) 234-5678",
    coordinates: { lat: 40.7128, lng: -74.006 },
    amenities: ["Hiking Trails", "Picnic Areas", "Nature Center", "Playground", "Restrooms", "Parking"],
    featured: true,
  },
  {
    id: "historic-downtown",
    name: "Historic Downtown District",
    category: "Cultural & Historic",
    shortDescription: "Charming Victorian-era buildings housing unique shops, restaurants, and galleries.",
    fullDescription:
      "Step back in time as you stroll through Maplewood's Historic Downtown District. This beautifully preserved collection of Victorian-era buildings has been the heart of our community since the 1850s. Today, the district is home to over 50 unique boutiques, artisan shops, farm-to-table restaurants, and galleries showcasing local artists. The cobblestone Main Street is lined with gas-style lamps and seasonal flower displays, creating a picturesque setting for shopping, dining, and people-watching. Every Saturday, the district hosts the famous Maplewood Farmers Market, featuring local produce, crafts, and live music.",
    image: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hours: "Shops: 10AM-6PM (varies by store)",
    admission: "Free to explore",
    address: "Main Street, Downtown Maplewood",
    phone: "(555) 345-6789",
    coordinates: { lat: 40.7138, lng: -74.008 },
    amenities: ["Shopping", "Dining", "Art Galleries", "Street Parking", "Public Restrooms", "WiFi Hotspots"],
    featured: true,
  },
  {
    id: "maplewood-museum",
    name: "Maplewood Heritage Museum",
    category: "Museums",
    shortDescription: "Explore 175 years of local history through interactive exhibits and rare artifacts.",
    fullDescription:
      "The Maplewood Heritage Museum is housed in the beautifully restored 1892 Carnegie Library building, a stunning example of Romanesque Revival architecture. The museum's permanent collection spans the entire history of Maplewood, from its founding by settlers in 1847 through its industrial heyday to the present day. Interactive exhibits bring history to life, allowing visitors to experience a recreated 1900s general store, operate a vintage printing press, and explore the stories of notable Maplewood residents. The museum also features rotating exhibitions showcasing different aspects of regional history and culture.",
    image: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hours: "Tue-Sat: 10AM-5PM, Sun: 12PM-4PM",
    admission: "Adults $12, Seniors $10, Students $8, Children under 5 free",
    address: "45 Museum Row, Maplewood",
    phone: "(555) 456-7890",
    coordinates: { lat: 40.7118, lng: -74.004 },
    amenities: ["Gift Shop", "Café", "Wheelchair Accessible", "Audio Tours", "Group Tours", "Research Library"],
    featured: true,
  },
  {
    id: "riverside-amphitheater",
    name: "Riverside Amphitheater",
    category: "Entertainment",
    shortDescription: "Open-air venue hosting concerts, theater performances, and community events.",
    fullDescription:
      "Set against the stunning backdrop of the Maple River, the Riverside Amphitheater is Maplewood's premier outdoor entertainment venue. The 3,500-seat amphitheater features state-of-the-art sound and lighting systems while maintaining an intimate atmosphere that connects performers with audiences. From spring through fall, the venue hosts an eclectic mix of concerts, theatrical productions, film screenings, and community celebrations. The surrounding grounds include landscaped gardens, food vendor areas, and riverside walking paths perfect for pre-show strolls.",
    image: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hours: "Event-based (Box Office: 10AM-6PM)",
    admission: "Varies by event",
    address: "800 Riverside Drive, Maplewood",
    phone: "(555) 567-8901",
    coordinates: { lat: 40.7148, lng: -74.002 },
    amenities: ["Concessions", "VIP Seating", "Accessible Seating", "Parking", "Lawn Seating", "Picnic Areas"],
    featured: false,
  },
  {
    id: "botanical-gardens",
    name: "Maplewood Botanical Gardens",
    category: "Parks & Recreation",
    shortDescription: "12 acres of curated gardens featuring native plants and exotic species.",
    fullDescription:
      "The Maplewood Botanical Gardens offer a horticultural haven spanning 12 meticulously maintained acres. Established in 1923, the gardens feature distinct themed areas including the Rose Garden with over 200 varieties, the Japanese Zen Garden, the Native Wildflower Meadow, and the impressive Victorian Conservatory housing tropical and desert plants. Educational programs, guided tours, and seasonal events make the gardens a living classroom for visitors of all ages. The on-site Garden Café serves farm-fresh meals overlooking the reflecting pond.",
    image: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hours: "Daily: 9AM-6PM (Extended hours in summer)",
    admission: "Adults $15, Seniors $12, Children $8",
    address: "350 Garden Lane, Maplewood",
    phone: "(555) 678-9012",
    coordinates: { lat: 40.7098, lng: -74.01 },
    amenities: [
      "Garden Café",
      "Gift Shop",
      "Guided Tours",
      "Photography Permits",
      "Event Rentals",
      "Wheelchair Accessible",
    ],
    featured: true,
  },
  {
    id: "old-mill-brewery",
    name: "Old Mill Craft Brewery",
    category: "Food & Drink",
    shortDescription: "Historic grain mill converted into award-winning craft brewery and restaurant.",
    fullDescription:
      "Housed in a beautifully restored 1870s grain mill, Old Mill Craft Brewery has become a destination for craft beer enthusiasts and food lovers alike. The brewery produces over 20 distinct beers using traditional methods and locally sourced ingredients, including hops grown on-site. Tours offer a behind-the-scenes look at the brewing process, from grain to glass. The adjoining restaurant serves elevated pub fare featuring ingredients from local farms, paired perfectly with their signature brews. The outdoor beer garden overlooks the mill pond and working waterwheel.",
    image: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    hours: "Mon-Thu: 11AM-10PM, Fri-Sat: 11AM-12AM, Sun: 11AM-9PM",
    admission: "Free (Tours: $15)",
    address: "275 Mill Creek Road, Maplewood",
    phone: "(555) 789-0123",
    coordinates: { lat: 40.7158, lng: -74.012 },
    amenities: ["Restaurant", "Brewery Tours", "Beer Garden", "Live Music", "Private Events", "Gift Shop"],
    featured: false,
  },
]

export const institutions = [
  {
    id: "maplewood-university",
    name: "Maplewood University",
    type: "University",
    established: 1892,
    students: 8500,
    description:
      "A prestigious liberal arts university known for its strong programs in environmental science, creative writing, and business administration. The 150-acre campus features historic Gothic architecture alongside modern facilities.",
    image: "/placeholder.svg?height=500&width=800",
    programs: [
      "Environmental Science",
      "Creative Writing",
      "Business Administration",
      "Computer Science",
      "Psychology",
      "Fine Arts",
    ],
    website: "https://example.com",
    address: "100 University Drive, Maplewood",
    phone: "(555) 100-2000",
  },
  {
    id: "maplewood-community-college",
    name: "Maplewood Community College",
    type: "Community College",
    established: 1965,
    students: 4200,
    description:
      "Offering accessible, quality education with over 60 degree and certificate programs. Known for excellent workforce development partnerships and transfer agreements with regional universities.",
    image: "/placeholder.svg?height=500&width=800",
    programs: [
      "Nursing",
      "Culinary Arts",
      "Information Technology",
      "Early Childhood Education",
      "Automotive Technology",
      "Graphic Design",
    ],
    website: "https://example.com",
    address: "500 College Avenue, Maplewood",
    phone: "(555) 200-3000",
  },
  {
    id: "maplewood-technical-institute",
    name: "Maplewood Technical Institute",
    type: "Technical School",
    established: 1978,
    students: 1800,
    description:
      "Specialized vocational training focused on skilled trades and emerging technologies. Industry partnerships ensure curriculum stays current with workforce needs.",
    image: "/placeholder.svg?height=500&width=800",
    programs: ["Welding", "Electrical", "HVAC", "CNC Machining", "Renewable Energy", "Cybersecurity"],
    website: "https://example.com",
    address: "750 Trade Street, Maplewood",
    phone: "(555) 300-4000",
  },
]

export const events = [
  {
    id: 1,
    name: "Maple Festival",
    date: "October 15-17, 2026",
    description:
      "Annual celebration of autumn with maple syrup tastings, craft vendors, live music, and the famous Maple Pie Contest.",
    location: "Downtown & Maple Grove Park",
    image: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 2,
    name: "Summer Concert Series",
    date: "June-August 2026",
    description:
      "Free weekly concerts every Friday evening at Riverside Amphitheater featuring local and regional musicians.",
    location: "Riverside Amphitheater",
    image: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 3,
    name: "Heritage Days",
    date: "July 4th Weekend",
    description:
      "Three-day celebration of Maplewood's history with reenactments, parades, fireworks, and family activities.",
    location: "Various Locations",
    image: "/placeholder.svg?height=300&width=500",
  },
  {
    id: 4,
    name: "Winter Wonderland Market",
    date: "December 1-23, 2026",
    description:
      "Enchanting holiday market featuring local artisans, seasonal treats, ice skating, and visits with Santa.",
    location: "Historic Downtown",
    image: "/placeholder.svg?height=300&width=500",
  },
]

export const historyTimeline = [
  {
    year: 1847,
    title: "Town Founded",
    description:
      "Settlers establish Maplewood along the banks of Maple River, drawn by fertile land and abundant maple forests.",
  },
  {
    year: 1852,
    title: "First Mill Built",
    description: "The original grain mill is constructed, becoming the economic heart of the growing community.",
  },
  {
    year: 1867,
    title: "Railroad Arrives",
    description:
      "The Maple Valley Railroad reaches town, spurring rapid growth and connecting Maplewood to major markets.",
  },
  {
    year: 1892,
    title: "University Founded",
    description: "Maplewood University opens its doors, establishing the town as a center of learning and culture.",
  },
  {
    year: 1923,
    title: "Botanical Gardens",
    description:
      "The Maplewood Botanical Gardens are established through a generous donation from the Thornwood family.",
  },
  {
    year: 1956,
    title: "Historic Preservation",
    description:
      "Downtown district is designated as a historic preservation area, protecting its Victorian architecture.",
  },
  {
    year: 1998,
    title: "Arts Renaissance",
    description: "Opening of the Riverside Amphitheater sparks a cultural renaissance in the community.",
  },
  {
    year: 2020,
    title: "Sustainable Future",
    description: "Maplewood achieves carbon-neutral status and is recognized as one of America's greenest small towns.",
  },
]

export const cultureHighlights = [
  {
    title: "Arts & Crafts Heritage",
    description:
      "Maplewood has a thriving arts community with galleries, studios, and regular art walks showcasing local talent.",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    title: "Farm-to-Table Movement",
    description:
      "Our restaurants pride themselves on sourcing ingredients from local farms, creating a vibrant culinary scene.",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    title: "Music & Performance",
    description:
      "From bluegrass jams to classical concerts, music is woven into the fabric of daily life in Maplewood.",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    title: "Community Traditions",
    description: "Annual festivals, parades, and gatherings bring residents together to celebrate our shared heritage.",
    image: "/placeholder.svg?height=400&width=600",
  },
]
